import '../../../data/datacorse/static/model/order_model.dart';

List<OrderModel> dummyOrderList = [
  OrderModel(
    orderId: '1001',
    orderUserDevicetoken: 'device_token_001',
    orderUserid: 'user_001',
    orderCoupon: 'SAVE10',
    orderAddress: 'شارع النيل، القاهرة',
    orderType: 'delivery',
    orderPriceDelivery: '25.00',
    orderDatetime: '2025-11-17 10:30:00',
    orderPrice: '150.00',
    orderTotalPrice: '175.00',
    orderPaymentMethod: 'cash',
    orderStatus: '0',
    orderDelivery: 'delivery_001',
    orderRating: '5',
    orderRatingComment: 'ممتاز جداً',
    addressId: 'addr_001',
    addressUserid: 'user_001',
    addressName: 'المنزل',
    addressCity: 'القاهرة',
    addressStreet: 'شارع النيل',
    addressLat: '30.0444',
    addressLang: '31.2357',
  ),
  OrderModel(
    orderId: '1001',
    orderUserDevicetoken: 'device_token_001',
    orderUserid: 'user_001',
    orderCoupon: 'SAVE10',
    orderAddress: 'شارع النيل، القاهرة',
    orderType: 'delivery',
    orderPriceDelivery: '25.00',
    orderDatetime: '2025-11-17 10:30:00',
    orderPrice: '150.00',
    orderTotalPrice: '175.00',
    orderPaymentMethod: 'cash',
    orderStatus: '0',
    orderDelivery: 'delivery_001',
    orderRating: '5',
    orderRatingComment: 'ممتاز جداً',
    addressId: 'addr_001',
    addressUserid: 'user_001',
    addressName: 'المنزل',
    addressCity: 'القاهرة',
    addressStreet: 'شارع النيل',
    addressLat: '30.0444',
    addressLang: '31.2357',
  ),
  OrderModel(
    orderId: '1001',
    orderUserDevicetoken: 'device_token_001',
    orderUserid: 'user_001',
    orderCoupon: 'SAVE10',
    orderAddress: 'شارع النيل، القاهرة',
    orderType: 'delivery',
    orderPriceDelivery: '25.00',
    orderDatetime: '2025-11-17 10:30:00',
    orderPrice: '150.00',
    orderTotalPrice: '175.00',
    orderPaymentMethod: 'cash',
    orderStatus: '0',
    orderDelivery: 'delivery_001',
    orderRating: '5',
    orderRatingComment: 'ممتاز جداً',
    addressId: 'addr_001',
    addressUserid: 'user_001',
    addressName: 'المنزل',
    addressCity: 'القاهرة',
    addressStreet: 'شارع النيل',
    addressLat: '30.0444',
    addressLang: '31.2357',
  ),
  OrderModel(
    orderId: '1002',
    orderUserDevicetoken: 'device_token_002',
    orderUserid: 'user_002',
    orderCoupon: 'SAVE20',
    orderAddress: 'شارع التحرير، الجيزة',
    orderType: 'pickup',
    orderPriceDelivery: '0.00',
    orderDatetime: '2025-11-16 14:15:00',
    orderPrice: '250.00',
    orderTotalPrice: '250.00',
    orderPaymentMethod: 'card',
    orderStatus: '1',
    orderDelivery: 'delivery_002',
    orderRating: '4',
    orderRatingComment: 'جيد',
    addressId: 'addr_002',
    addressUserid: 'user_002',
    addressName: 'العمل',
    addressCity: 'الجيزة',
    addressStreet: 'شارع التحرير',
    addressLat: '30.0131',
    addressLang: '31.2089',
  ),
  OrderModel(
    orderId: '1003',
    orderUserDevicetoken: 'device_token_003',
    orderUserid: 'user_003',
    orderCoupon: null,
    orderAddress: 'شارع قصر العيني، وسط البلد',
    orderType: 'delivery',
    orderPriceDelivery: '30.00',
    orderDatetime: '2025-11-15 09:45:00',
    orderPrice: '180.00',
    orderTotalPrice: '210.00',
    orderPaymentMethod: 'cash',
    orderStatus: '3',
    orderDelivery: null,
    orderRating: null,
    orderRatingComment: null,
    addressId: 'addr_003',
    addressUserid: 'user_003',
    addressName: 'المتجر',
    addressCity: 'القاهرة',
    addressStreet: 'شارع قصر العيني',
    addressLat: '30.0596',
    addressLang: '31.2453',
  ),
  OrderModel(
    orderId: '1004',
    orderUserDevicetoken: 'device_token_004',
    orderUserid: 'user_004',
    orderCoupon: 'VIP15',
    orderAddress: 'شارع البطل أحمد عبدالعزيز، المقطم',
    orderType: 'delivery',
    orderPriceDelivery: '20.00',
    orderDatetime: '2025-11-14 16:20:00',
    orderPrice: '320.00',
    orderTotalPrice: '340.00',
    orderPaymentMethod: 'card',
    orderStatus: '4',
    orderDelivery: 'delivery_004',
    orderRating: null,
    orderRatingComment: null,
    addressId: 'addr_004',
    addressUserid: 'user_004',
    addressName: 'الفيلا',
    addressCity: 'القاهرة',
    addressStreet: 'شارع البطل أحمد عبدالعزيز',
    addressLat: '29.9822',
    addressLang: '31.2801',
  ),
];
