final List<Map<String, dynamic>> dummyItems = [
  {
    'name': 'Smartphone',
    'nameAr': 'هاتف ذكي',
    'desc': 'Latest model smartphone with high performance.',
    'descAr': 'أحدث طراز من الهواتف الذكية عالية الأداء.',
    'count': 15,
    'available': true,
    'timeAdded': DateTime.now().subtract(const Duration(days: 1)).toString(),
    'icon': 'assets/svg/phone.svg',
  },
  {
    'name': 'Running Shoes',
    'nameAr': 'حذاء جري',
    'desc': 'Comfortable and durable running shoes.',
    'descAr': 'أحذية جري مريحة ومتينة.',
    'count': 30,
    'available': true,
    'timeAdded': DateTime.now().subtract(const Duration(days: 2)).toString(),
    'icon': 'assets/svg/shose.svg',
  },
  {
    'name': 'Evening Dress',
    'nameAr': 'فستان سهرة',
    'desc': 'Elegant evening dress for special occasions.',
    'descAr': 'فستان سهرة أنيق للمناسبات الخاصة.',
    'count': 8,
    'available': false,
    'timeAdded': DateTime.now().subtract(const Duration(days: 3)).toString(),
    'icon': 'assets/svg/dress.svg',
  },
  {
    'name': 'Laptop',
    'nameAr': 'حاسوب محمول',
    'desc': 'High-performance laptop suitable for work and gaming.',
    'descAr': 'حاسوب محمول عالي الأداء مناسب للعمل والألعاب.',
    'count': 5,
    'available': true,
    'timeAdded': DateTime.now().subtract(const Duration(days: 5)).toString(),
    'icon': 'assets/svg/phone.svg',
  },
  {
    'name': 'Kids Shoes',
    'nameAr': 'أحذية أطفال',
    'desc': 'Lightweight and comfortable shoes for kids.',
    'descAr': 'أحذية خفيفة ومريحة للأطفال.',
    'count': 22,
    'available': true,
    'timeAdded': DateTime.now().subtract(const Duration(hours: 10)).toString(),
    'icon': 'assets/svg/shose.svg',
  },
  {
    'name': 'Casual Dress',
    'nameAr': 'فستان كاجوال',
    'desc': 'Casual dress suitable for daily wear.',
    'descAr': 'فستان كاجوال مناسب للارتداء اليومي.',
    'count': 12,
    'available': true,
    'timeAdded': DateTime.now().subtract(const Duration(days: 7)).toString(),
    'icon': 'assets/svg/dress.svg',
  },
  {
    'name': 'Bluetooth Earbuds',
    'nameAr': 'سماعات بلوتوث',
    'desc': 'Wireless earbuds with noise cancellation.',
    'descAr': 'سماعات لاسلكية مع خاصية إلغاء الضوضاء.',
    'count': 50,
    'available': true,
    'timeAdded': DateTime.now().subtract(const Duration(hours: 5)).toString(),
    'icon': 'assets/svg/phone.svg',
  },
  {
    'name': 'Sport Shoes',
    'nameAr': 'أحذية رياضية',
    'desc': 'Sport shoes for training and daily activities.',
    'descAr': 'أحذية رياضية للتدريب والأنشطة اليومية.',
    'count': 18,
    'available': false,
    'timeAdded': DateTime.now().subtract(const Duration(days: 11)).toString(),
    'icon': 'assets/svg/shose.svg',
  },
];
