// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyV34YcgxVHWXE18WeShl4Elh_nJz2cuk',
    appId: '1:615173374977:web:53a65d2530f3292000ac00',
    messagingSenderId: '615173374977',
    projectId: 'ecommerce-fe1eb',
    authDomain: 'ecommerce-fe1eb.firebaseapp.com',
    storageBucket: 'ecommerce-fe1eb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTgej12X3ID8ICiD8G2J_s4hDKPNkszRk',
    appId: '1:615173374977:android:0f54b544c6e9b6b700ac00',
    messagingSenderId: '615173374977',
    projectId: 'ecommerce-fe1eb',
    storageBucket: 'ecommerce-fe1eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEAA9beKdETPu-CV7NFUxkN0sQrVH1K9w',
    appId: '1:615173374977:ios:06ca3bb29e0ad2c500ac00',
    messagingSenderId: '615173374977',
    projectId: 'ecommerce-fe1eb',
    storageBucket: 'ecommerce-fe1eb.firebasestorage.app',
    iosBundleId: 'com.example.souqAlKhamisAdminVersion',
  );
}
